apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: k8s-client-tool-exec
  annotations:
    app.accuknox.com/type: harden
  namespace: container_namespace
spec:
  selector:
    matchLabels:
      kubearmor.io/container.name: test-container # change with your container name
  action: Audit
  severity: 5
  message: "Detected execution of Kubernetes client tools or container runtime CLIs"
  process:
    matchPaths:
    # Container runtime CLIs
    - execname: crictl
    - execname: docker
    - execname: ctr
    - execname: nerdctl
    - execname: podman
  tags:
  - MITRE_T1609_CONTAINER_ADMINISTRATION_COMMAND
  - NIST_800-53_AU-2
  - PCI_DSS_7.2.1
