apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: cronjob-cfg
  annotations:
    app.accuknox.com/type: harden
spec:
  selector:
    matchLabels:
      kubearmor.io/container.name: test-container # change with your container name
  message: "Detected access to cron job files/directories"
  severity: 5
  file:
    matchDirectories:
    - dir: /etc/cron.d/
      recursive: true
    - dir: /etc/cron.daily/
      recursive: true
    - dir: /etc/cron.hourly/
      recursive: true
    - dir: /etc/cron.monthly/
      recursive: true
    - dir: /etc/cron.weekly/
      recursive: true
    - dir: /var/cron/
      recursive: true
    - dir: /var/spool/cron/
      recursive: true
    matchPaths:
    - path: /etc/crontab
      readOnly: true
    - path: /etc/anacrontab
      readOnly: true
    - path: /etc/cron.allow
      readOnly: true
    - path: /etc/cron.deny
      readOnly: true
  action: Audit
  tags:
  - MITRE_T1053_SCHEDULED_TASK
  - NIST_800-53_SI-4
  - PCI_DSS_6.4
