apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: audit-external-device
  annotations:
    app.accuknox.com/type: harden
  namespace: container_namespace
spec:
  selector:
    matchLabels:
      kubearmor.io/container.name: test-container # change with your container name
  action: Audit
  severity: 3
  message: "Detected modification of external device access"
  process:
    matchPaths:
    - execname: mount
    - execname: umount
    - execname: fdisk
    - execname: cfdisk
    - execname: sfdisk
    - execname: parted
    - execname: mkfs
    - execname: fsck
    - execname: lsblk
    - execname: blkid
    - execname: losetup
    - execname: kpartx
    - execname: qemu-nbd
    - execname: mountpoint
  tags:
  - MITRE_T1091_REPLICATION_THROUGH_REMOVABLE_MEDIA
  - NIST_DE.CM-1
  - PCI_DSS_10.2.3
