apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: harden-crypto-miners 
spec:
  severity: 10
  message: "Cryptominer detected and blocked"
  action: Block

  process:
    matchDirectories:
      - dir: /tmp/
        recursive: true
    matchPaths:
      - execname: dero-miner-linux-amd64
      - execname: dero-wallet-cli-linux-amd64
      - execname: dero
      - execname: derod-linux-amd64
      - execname: masscan
      - execname: nmap
      - execname: ntpdate
      - execname: xmrig
      - execname: zgrab2

  selector:
    matchLabels:
      kubearmor.io/container.name: "ubuntu-VD"  # Replace with your container name

  tags:
    - MITRE
    - MITRE_T1496_resource_hijacking
    - NIST
    - NIST_800-53_SI-4
