apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: harden-system-owner-discovery-ubuntu  # Replace with your container name
spec:
  severity: 3
  message: "System owner discovery command execution denied"
  action: Audit

  process:
    matchPaths:
      - path: /usr/bin/id
      - path: /usr/bin/w
      - path: /usr/bin/who
      - path: /usr/bin/whoami

  selector:
    matchLabels:
      kubearmor.io/container.name: "ubuntu-VD"  # Replace with your container name if needed

  tags:
    - MITRE
    - MITRE_T1082_system_information_discovery
