apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: harden-file-integrity 
spec:
  severity: 1
  message: "Detected and prevented compromise to File integrity"
  action: Block

  file:
    matchDirectories:
      - dir: /bin/
        readOnly: true
        recursive: true
      - dir: /boot/
        readOnly: true
        recursive: true
      - dir: /sbin/
        readOnly: true
        recursive: true
      - dir: /usr/bin/
        readOnly: true
        recursive: true
      - dir: /usr/lib/
        readOnly: true
        recursive: true
      - dir: /usr/sbin/
        readOnly: true
        recursive: true

  selector:
    matchLabels:
      kubearmor.io/container.name: "ubuntu-VD"  # Replace with your container name

  tags:
    - MITRE
    - MITRE_T1036_masquerading
    - MITRE_T1565_data_manipulation
    - NIST
    - NIST_800-53_AU-2
    - NIST_800-53_SI-4
