apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: harden-write-etc-dir-ubuntu # Replace with your container name
spec:
  severity: 5
  message: "Alert! File creation under /etc/ directory detected."
  action: Block

  file:
    matchDirectories:
      - dir: /etc/
        readOnly: true
        recursive: true

  selector:
    matchLabels:
      kubearmor.io/container.name: "ubuntu-VD"  # Replace with your container name

  tags:
    - MITRE
    - MITRE_T1036.005_match_legitimate_name_or_location
    - MITRE_T1036_masquerading
    - MITRE_T1562.001_disable_or_modify_tools
    - MITRE_TA0003_persistence
    - MITRE_TA0005_defense_evasion
    - NIST
    - NIST_800-53
    - NIST_800-53_SI-4
    - NIST_800-53_SI-7
