apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: harden-trusted-cert-mod-ubuntu # Replace with your container name
spec:
  severity: 1
  message: "Credentials modification denied"
  action: Block

  file:
    matchDirectories:
      - dir: /etc/pki/
        readOnly: true
        recursive: true
      - dir: /etc/ssl/
        readOnly: true
        recursive: true
      - dir: /usr/local/share/ca-certificates/
        readOnly: true
        recursive: true

  selector:
    matchLabels:
      kubearmor.io/container.name: "ubuntu-VD"  # Replace with your container name

  tags:
    - FGT1555
    - FIGHT
    - MITRE
    - MITRE_T1552_unsecured_credentials
