apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: impair-defense
  annotations:
    app.accuknox.com/type: harden
spec:
  selector:
    matchLabels:
      kubearmor.io/container.name: test-container # change with your container name
  action: Block
  severity: 6
  message: "Detected unauthorized attempt to modify SELinux/AppArmor policy files"
  file:
    matchDirectories:
    - dir: /etc/apparmor.d/
      recursive: true
      readOnly: true
    - dir: /etc/sysconfig/selinux/
      recursive: true
      readOnly: true
    matchPaths:
    - path: /etc/selinux/semanage.conf
      readOnly: true
  tags:
  - MITRE_T1562_001_IMPAIR_DEFENSES
  - NIST_RS.MI-1
  - PCI_DSS_11.5.1
